//test route for user creation
PUT http://localhost:9000/api/user
Content-Type: application/json

{
  "username": "johndo",
  "email": "joasdsdssddsdhsdsdnasdsdasdaasdsadsdasdasdoae@xample.com",
  "password_hash": "securehDashedpa.ssword123",
  "first_name": "John",
  "last_name": "Doe",
  "date_of_birth": "1990-05-15T00:00:00Z"
}

###

PUT http://localhost:9000/api/user
Content-Type: application/json

{
  "username": "janesmitasdasdh",
  "email": "janesmith@examp.le.com",
  "password_hash": "anothers.trong123hashABC",
  "first_name": "Jane",
  "last_name": "Smith",
  "date_of_birth": "1988-11-22T00:00:00Z"
}

###

PUT  http://localhost:9000/api/user
Content-Type: application/json

{
  "username": "testuser",
  "email": "valid.email@example.com",
  "password_hash": "mysecurepa213.Wssword",
  "first_name": "Test",
  "last_name": "User",
  "date_of_birth": "2000-01-01T00:00:00Z"
}