@host = localhost:9000

### Test Case 1: Successful User Creation
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "newuser123",
  "email": "newuser123@example.com",
  "password": "troAngassword!123",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 2: Malformed json
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "newuser123",
  "email": "newuser123@example.com",
  "password": "troAngassword!123"
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 3: Malformed json
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "newuser123",
  "email": "newuser123@example.com",
  "password" "troAngassword!123",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 4: Malformed json
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username: "newuser123",
  "email": "newuser123@example.com",
  "password": "troAngassword!123",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}


### Test Case 5: Malformed json
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "newuser123,
  "email": "newuser123@example.com",
  "password": "troAngassword!123",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 6: no body
POST http://{{host}}/api/user
Content-Type: application/json

### Test Case 7: type mismatch for username
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": 14,
  "email": "newuser123@example.com",
  "password": "troAngassword!123",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 8: Unknown Field
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "newuser123",
  "email": "newuser123@example.com",
  "password": "troAngassword!123",
  "dateOfBirth": "1995-10-26T00:00:00Z",
  "unnecessaryField": "someValue"
}



### Test Case 9: Invalid username too short
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "a",
  "email": "newuser123@example.com",
  "password": "troAngassword!123",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 10: Invalid username too long
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "aasdasdassdsaasdsdasd",
  "email": "newuser123@example.com",
  "password": "troAngassword!123",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 11: Invalid username format
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "aas/d",
  "email": "newuser123@example.com",
  "password": "troAngassword!123",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 12: Invalid email format
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "aasdas",
  "email": "newuser123example.com",
  "password": "troAngassword!123",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 13: Invalid email max length for rfc complience
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "aasdas",
  "email": "Thisisateststraaaaaaaaaasssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaingforlengthvaliasdasdasdaaaaaasssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssdationpurposes.Itcontainsmanymorecharacters.asdasdasdasdasdasdasdasdasdasdsdadasdasdasdasd.asdasdasdasdasdasdasdasd.asdasdasdasdasdasdasdasdasdasd.asdasdasdasdasdasdasdasd.asdasdasdasdasdasdasdasdasdasd.asdasdasdasdasdasd@asd.du",
  "password": "troAngassword!123",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 14: Invalid password too short
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "asdasda",
  "email": "newuser123@example.com",
  "password": "!123",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 14: Invalid password too long
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "asdasda",
  "email": "newuser123@example.com",
  "password": "!123aasdsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssasdA",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 14: Invalid password format
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "asdasda",
  "email": "newuser123@example.com",
  "password": "!123aasdsssssssssssssssssssssssssssssssssssssssasd",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 15: Invalid dob
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "aasdasd",
  "email": "newuser123@example.com",
  "password": "troAngassword!123",
  "dateOfBirth": "2022-10-26T00:00:00Z"
}

### Test Case 16: Missing required key username
POST http://{{host}}/api/user
Content-Type: application/json

{
  "email": "newuser123@example.com",
  "password": "troAngassword!123",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 17: Missing required key email
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "aasdasd",
  "password": "troAngassword!123",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}


### Test Case 18: Missing required key password
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "aasdasd",
  "email": "newuser123@example.com",
  "dateOfBirth": "1995-10-26T00:00:00Z"
}

### Test Case 19: Missing required key dob
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "aasdasd",
  "email": "newuser123@example.com",
  "password": "troAngassword!123"
}


### Test Case 20 exatly 18 years old from the test
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "minageuser",
  "email": "minage@example.com",
  "password": "troAngassword!123",
  "dateOfBirth": "2009-07-07T00:00:00Z" 
}

### Test Case 20 not 16 years old
POST http://{{host}}/api/user
Content-Type: application/json

{
  "username": "one_day_younger",
  "email": "onedayyounger@example.com",
  "password": "troAngassword!123",
  "dateOfBirth": "2009-07-9T00:00:00Z"
}



