// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                    uuid.UUID          `json:"id"`
	Username              string             `json:"username"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	FirstName             pgtype.Text        `json:"first_name"`
	LastName              pgtype.Text        `json:"last_name"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	LastOnline            pgtype.Timestamptz `json:"last_online"`
	Bio                   pgtype.Text        `json:"bio"`
	DateOfBirth           time.Time          `json:"date_of_birth"`
	IsVerified            pgtype.Bool        `json:"is_verified"`
	ProfilePictureAssetID pgtype.UUID        `json:"profile_picture_asset_id"`
}
