// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO "user" (
    id, 
    username, 
    email, 
    password_hash, 
    date_of_birth
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5 
)
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	DateOfBirth  time.Time `json:"date_of_birth"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DateOfBirth,
	)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, bio, profile_picture_asset_id
FROM "user"
WHERE id = $1
LIMIT 1
`

type GetUserRow struct {
	ID                    uuid.UUID   `json:"id"`
	Username              string      `json:"username"`
	Bio                   pgtype.Text `json:"bio"`
	ProfilePictureAssetID pgtype.UUID `json:"profile_picture_asset_id"`
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Bio,
		&i.ProfilePictureAssetID,
	)
	return i, err
}
